/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as FilesImport } from './routes/files'
import { Route as EnginesImport } from './routes/engines'
import { Route as AccountsImport } from './routes/accounts'
import { Route as IndexImport } from './routes/index'
import { Route as DatabasesIndexImport } from './routes/databases/index'
import { Route as DatabasesDatabaseIdImport } from './routes/databases/$databaseId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const FilesRoute = FilesImport.update({
  path: '/files',
  getParentRoute: () => rootRoute,
} as any)

const EnginesRoute = EnginesImport.update({
  path: '/engines',
  getParentRoute: () => rootRoute,
} as any)

const AccountsRoute = AccountsImport.update({
  path: '/accounts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DatabasesIndexRoute = DatabasesIndexImport.update({
  path: '/databases/',
  getParentRoute: () => rootRoute,
} as any)

const DatabasesDatabaseIdRoute = DatabasesDatabaseIdImport.update({
  path: '/databases/$databaseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsImport
      parentRoute: typeof rootRoute
    }
    '/engines': {
      id: '/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof EnginesImport
      parentRoute: typeof rootRoute
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/databases/$databaseId': {
      id: '/databases/$databaseId'
      path: '/databases/$databaseId'
      fullPath: '/databases/$databaseId'
      preLoaderRoute: typeof DatabasesDatabaseIdImport
      parentRoute: typeof rootRoute
    }
    '/databases/': {
      id: '/databases/'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AccountsRoute,
  EnginesRoute,
  FilesRoute,
  SettingsRoute,
  DatabasesDatabaseIdRoute,
  DatabasesIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/accounts",
        "/engines",
        "/files",
        "/settings",
        "/databases/$databaseId",
        "/databases/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/accounts": {
      "filePath": "accounts.tsx"
    },
    "/engines": {
      "filePath": "engines.tsx"
    },
    "/files": {
      "filePath": "files.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/databases/$databaseId": {
      "filePath": "databases/$databaseId.tsx"
    },
    "/databases/": {
      "filePath": "databases/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
